export const NETWORK_GRAPH_MAP = {
    mainnet: 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/FrwziBsTDBogUj57ts4U1kx5X5hDMkpX5STpUXphomyV',
    matic: 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/Ga4gCEvJGuu7Y2oXCbpa3R9KMNBXWYLg1kJPxnfeu5fb',
    optimism: 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/HxvH1S81KFam6J7etqtxngjLPhZMS5QcHKwPa7LVz1no',
    "optimism-sepolia": "https://api.studio.thegraph.com/query/45842/opt-sep-jiffy-scan/version/latest",
    "arbitrum-one": 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/4YM6vwSP4Mx38qXsVh6TFyrWrKgm7zvX4mFGPS2L6afk',
    avalanche: 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/ALNXErAtAfjQU8TP39nitk6ej9ZtrDYmnXRYRdWiFuGZ',
    "avalanche-fuji": "https://api.studio.thegraph.com/query/45842/avalanche-fuji-jiffy-scan/version/latest/",
    "base-sepolia": "https://api.studio.thegraph.com/query/45842/base-sep-jiffy-scan/version/latest",
    fuse: 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/86D6T6o7YmB5MrSJhMU2Syeqt7r927yecSYcmJrpkTXn',
    base: 'https://gateway-arbitrum.network.thegraph.com/api/{API_KEY}/subgraphs/id/9KToKxWC5uRS5ecCFgAxrScDPU2rVMy3hp7abAkt6BED',
    sepolia: "https://api.studio.thegraph.com/query/45842/sepolia-jiffy-scan/version/latest",
    "arbitrum-sepolia":
        "https://gateway.thegraph.com/api/1afd1a1d48e26c2c6fed3465adb9b876/subgraphs/id/8bh2bxiNysQJtqwp1HbEMKPpKDYe5JYGnykGTpmprDWZ",
    "polygon-amoy": "https://api.studio.thegraph.com/query/24129/polygon-amoy-jiffy-scan/version/latest",
};

export const CHAINID_NETWORK_MAP = {
    1: "mainnet",
    137: "matic",
    10: "optimism",
    // 5: "goerli",
    // 80001: "mumbai",
    42161: "arbitrum-one",
    43114: "avalanche",
    43113: "avalanche-fuji",
    84532: "base-sepolia",
    // 100: "gnosis",
    // 56: "bsc",
    // 250: "fantom",
    // 4002: "fantom-testnet",
    // 122: "fuse",
    8453: "base",
    11155111: "sepolia",
    421614: "arbitrum-sepolia",
    // 97: "bnb-testnet",
    80002: "polygon-amoy",
    11155420: "optimism-sepolia",
    7560: "cyber-mainnet",
    // 78600: "vanar-testnet",
    // 2040: "vanar-mainnet",
    656476: "open-campus-test",
    911867: "odyssey",
};

